# Generated by Django 5.0.14 on 2025-09-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(default='INR', help_text='User preferred currency code (ISO 4217)', max_length=3, verbose_name='preferred currency'),
        ),
    ]
