# Generated by Django 5.0.14 on 2025-09-27 12:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('mutual_fund', 'Mutual Fund'), ('bond', 'Bond'), ('crypto', 'Cryptocurrency'), ('commodity', 'Commodity'), ('reit', 'REIT'), ('other', 'Other')], max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('day_change', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('day_change_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('volume', models.BigIntegerField(default=0)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'portfolios_asset',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='portfolios__symbol_2ce9d2_idx'), models.Index(fields=['asset_type'], name='portfolios__asset_t_e27e21_idx')],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gain_loss_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='core.familygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios_portfolio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gain_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('gain_loss_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolios.portfolio')),
            ],
            options={
                'db_table': 'portfolios_holding',
                'unique_together': {('portfolio', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('split', 'Stock Split'), ('merger', 'Merger'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolios.holding')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios_transaction',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assets', models.ManyToManyField(related_name='watchlists', to='portfolios.asset')),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='core.familygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios_watchlist',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='portfolios.asset')),
            ],
            options={
                'db_table': 'portfolios_price_history',
                'ordering': ['-date'],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
