# Generated by Django 5.0.14 on 2025-09-28 01:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_migrate_existing_currency_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SIP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name for this SIP', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100'))])),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for indefinite SIP', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('next_investment_date', models.DateField()),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_units', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('returns_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('auto_invest', models.BooleanField(default=False, help_text='Automatically create investments on due dates')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sips', to='portfolios.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sips', to='portfolios.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolios_sip',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SIPInvestment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nav_price', models.DecimalField(decimal_places=4, help_text='NAV/Price at time of investment', max_digits=12)),
                ('units_allocated', models.DecimalField(decimal_places=6, max_digits=15)),
                ('current_nav', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('returns_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('sip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='portfolios.sip')),
            ],
            options={
                'db_table': 'portfolios_sip_investment',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='sip',
            index=models.Index(fields=['status', 'next_investment_date'], name='portfolios__status_e07ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='sip',
            index=models.Index(fields=['user', 'status'], name='portfolios__user_id_66ad52_idx'),
        ),
        migrations.AddIndex(
            model_name='sipinvestment',
            index=models.Index(fields=['sip', 'date'], name='portfolios__sip_id_9c4fc7_idx'),
        ),
    ]
